project '../PPColorfulSlider.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

def common_pods
    pod 'Masonry'
end

inhibit_all_warnings!

platform :ios, '8.0'

target 'PPColorfulSlider' do
    common_pods
end

# 解决一堆warning

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
